/*
 * Class auto generated by TexturePacker
 * 
 * Contains references to each image within the sprite sheet.
 *
 * http://www.codeandweb.com/texturepacker
 * $TexturePacker:SmartUpdate:f2ef8c4cc14144ed6837e9236d59ede6:703859ae7dc1a3985746aaad0e608f90:33509bb3a714716791e424b67cb95b8d$
 *
 */
namespace TexturePackerMonoGameDefinitions
{
	public class mainMenu
	{
		public const string MainMenu1 = "mainMenu1";
		public const string MainMenu2 = "mainMenu2";
		public const string MainMenu3 = "mainMenu3";
		public const string MainMenu4 = "mainMenu4";
		public const string MainMenu5 = "mainMenu5";
		public const string MainMenu6 = "mainMenu6";
		public const string MainMenu7 = "mainMenu7";
		public const string MainMenu8 = "mainMenu8";
		public const string MainMenu9 = "mainMenu9";
		public const string MainMenu10 = "mainMenu10";
		public const string MainMenu11 = "mainMenu11";
		public const string MainMenu12 = "mainMenu12";
		public const string MainMenu13 = "mainMenu13";
		public const string MainMenu14 = "mainMenu14";
	}
}