/*
 * Class auto generated by TexturePacker
 * 
 * Contains references to each image within the sprite sheet.
 *
 * http://www.codeandweb.com/texturepacker
 * $TexturePacker:SmartUpdate:7b9e0f437bf2f68233d5064696431ee6:703859ae7dc1a3985746aaad0e608f90:aad99d7f13f4c819e14f64f55a50db2f$
 *
 */
namespace TexturePackerMonoGameDefinitions
{
	public class unsaved
	{
		public const string MainMenu1 = "mainMenu1";
		public const string MainMenu2 = "mainMenu2";
		public const string MainMenu3 = "mainMenu3";
		public const string MainMenu4 = "mainMenu4";
		public const string MainMenu5 = "mainMenu5";
		public const string MainMenu6 = "mainMenu6";
		public const string MainMenu7 = "mainMenu7";
		public const string MainMenu8 = "mainMenu8";
		public const string MainMenu9 = "mainMenu9";
		public const string MainMenu10 = "mainMenu10";
		public const string MainMenu11 = "mainMenu11";
		public const string MainMenu12 = "mainMenu12";
		public const string MainMenu13 = "mainMenu13";
		public const string MainMenu14 = "mainMenu14";
	}
}