/*
 * Class auto generated by TexturePacker
 * 
 * Contains references to each image within the sprite sheet.
 *
 * http://www.codeandweb.com/texturepacker
 * $TexturePacker:SmartUpdate:b4b3457809b1894d9970692aedacf90f:0bed08842a824376363cf7d3ce9cb154:c2c65fcab905a0ce3eaff2295f73bf3c$
 *
 */
namespace TexturePackerMonoGameDefinitions
{
	public class unsaved
	{
		public const string IdlePlayer0 = "idlePlayer0";
		public const string IdlePlayer1 = "idlePlayer1";
		public const string IdlePlayer2 = "idlePlayer2";
		public const string IdlePlayer3 = "idlePlayer3";
	}
}